version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
       - echo "installing nodejs"
  pre_build:
    commands:
       - echo "we are in pre-build phase"
  build:
      commands:
         - echo "we are in build block"
         - echo "we are doing some test"
         - grep -Fq "Congratulations" index.html
  post_build:
    commands:
      - echo "we are in post build phase"
